### ISSUE TITLE
Wrong location info returned

### ISSUE THREAD

**Issue by danielegobbetti** [microg/NominatimGeocoderBackend#1]
Hello! I noticed that the location info returned (eg to gallery) are off by a couple of tens of kilometers. Is this a "blur" introduced for privacy reasons? I tried entering the coordinates into the online search form on the map quest website and the info shown there are exact.

**Comment by mar-v-in** [comment]
I usually do not get any offset at all and it is no intended feature to reduce accuracy. I'll look into that.

**Comment by danielegobbetti** [comment]
Do you want a geo-tagged photo to test?

For instance a photo geotagged with these coordinates: (Edit: removed for privacy reasons)
is shown in the gallery app (menu -> show details) as being shot here: http://www.openstreetmap.org/way/214800599 

If I choose (from the gallery app) "show photo on map" and open it in Osmand it shows the right coordinates.

**Comment by mar-v-in** [comment]
Thanks, that led me to the reason: 
Depending on your locale, numbers are formatted using different decimal marks, but the api requires to use a dot. Using comma will result in the number being cut off, the result shown is at geo coordinates (46,11), which is "slightly" off the real result.

I'll upload the fix soon

**Comment by danielegobbetti** [comment]
Cool, thanks!

**Comment by danielegobbetti** [comment]
Sorry to bug you, but could you tag the new release so that it gets picked up by f-droid? Thanks again!

**Comment by mar-v-in** [comment]
The 1.1 version will be released soon (like a few hours), just some testing of the newly added feature.
As always, release results in new tag

**Comment by danielegobbetti** [comment]
Understood, thanks again!

**Comment by aelmahmoudy** [comment]
@mar-v-in please make the tag matching the version v1.1.0 (not v1.1), that helps auto-updating the build in F-Droid

**Comment by mar-v-in** [comment]
@aelmahmoudy done, didn't know the exact tag makes a difference.

**Comment by aelmahmoudy** [comment]
Thanks !
