### ISSUE TITLE
OsmAndGeocoderBackend with a fallback to Natural Area Coding

### ISSUE THREAD

**Issue by steelman** [microg/NominatimGeocoderBackend#10]
If I understand correctly this code has became useless due to introduction of API keys. There seem to be no other free geocoding service. However, I can see some alternatives to make this service work again.

First, the reverse geocoding. It can be implemented with [Natural Area Coding System](http://www.nacgeo.com/nacsite/). Neither database nor network is required simply transform coordinates into a NAC string. For me, for example, it would be enough since all I want is to use "Location" sorting (grouping actually) in my gallery. There are two simple features that can improve usability of such "procedural reverse geocoding":
- adjustable accuracy so a user can choose how long/accurate the generated strings are,
- a user maintained dictionary of places with user defined radii.

The real geocoding is more tricky as it requires database. If I can be an example again, I've got [OsmAnd](http://osmand.net). It has its own offline maps and can do both geocoding and reverse geocoding at least inside the app. I am not sure if an API for this is exposed but I assume doing so wouldn't be too hard.

Of course the service would need to be renamed to OsmAndGeocoderBackend but that is rather trivial to do ;-)

**Comment by mar-v-in** [comment]
You can build this as a separate backend, that's why UnifiedNlp uses a plug-in system ;)
