### ISSUE TITLE
Crashes when enabling in kit kat

### ISSUE THREAD

**Issue by Locash** [microg/NominatimGeocoderBackend#25]
I receive an error when I attempt to enable it  in microG settings.  Never allowing it to be set up at all.
Any idea what might be going on?

**Comment by ale5000-git** [comment]
@Locash: Do you have version 1.2.2 installed?

**Comment by Locash** [comment]
@ale5000-git  No, I have 1.2.1 

Update :  I installed 1.2.2 from F-droid and that solved my problem. Thank you @ale5000-git for the reminder to always make sure to have the most recent version of an app.
