### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by IzzySoft** [microg/NominatimGeocoderBackend#29]
**Describe the bug**
As I see it reported throughout multiple issues here and comments elsewhere, it seems this backend is no longer working as expected. [Debugging a request to it](https://github.com/deckerst/aves/issues/70#issuecomment-1307931650) yields no results. Are there any plans to make it working again?

**To Reproduce**

Please see the above link. As I cannot find the backend's check in the microG self-test and, as a user, have no clue how to give proper steps, that's all I can say: there seem to be no results. I've watched the network traffic and did not even see any network requests being made when the Android `Geocoder` class was being called.

**Expected behavior**
A network request is being made, and the reverse-geocoding results are returned.

**Screenshots**
n/a

**System**
Android Version: 10
Device: Shift6mq
Custom ROM: ShiftOS-L 3.9 with microG installed "in UserSpace". All checkmarks in the self-test are green.

**Additional context**
See the linked issue. The gallery app Aves has the feature to group photos by location. For that it needs to reverse-geocode the coordinates as described above.

**Comment by SigmaBonder** [comment]
It works just fine on my device. Latest microG installed as a system app on Android 13.

**Comment by IzzySoft** [comment]
How do you test it?

**Comment by SigmaBonder** [comment]
See [here](https://github.com/deckerst/aves/issues/70#issuecomment-1308850850) — I used a custom [Aves](https://github.com/deckerst/aves) build, modified to use Android's `Geocoder` class.

**Comment by ale5000-git** [comment]
@SigmaBonder
@IzzySoft
If microG is installed correctly it should work as if GMS is really installed, so why the normal version doesn't work?

**Comment by IzzySoft** [comment]
@ale5000-git if I'd know how to reliably test it… The other location backends work fine, and this was the first time I had to explicitly use reverse-geocoding. From the debug (logcat) it seemed no data were returned. Sigma's test with the modified version was after I've opened this issue. To me it's still not clear where the issue is located – and as long as I cannot reliably test, it's hard to say. And concerning the difference: @SigmaBonder might be able to tell what the difference is, I have no clue…

@SigmaBonder I've tried that modified version (`aves-play-profile_20221109_1530_geocoder.apk`) as well, no dice.
Now tried it on a different device: surprise…

So it works on the FP2 running LineageOS for microG 18.1 (i.e. shipping with microG inside)/Android 11, but fails on the Shift6mq with microG installed in userspace (as per instructions in their board; all other backends working fine). Bummer.

I really wish microG self-check would cover geocoding modules as well.

**Comment by SigmaBonder** [comment]
@ale5000-git That's a good question. I didn't test it before with normal version, just went straight for the modified one (I didn't use Aves before). But now I installed both versions side by side and only the modified works.
[This comment](https://github.com/deckerst/aves/issues/70#issuecomment-1302153080) suggests that some sort of an optimization by @deckerst might be the cause — it seems that if the Play services are not detected, reverse geocoding is skipped entirely. But that raises the question: why aren't those detected, even though signatures are spoofed?

**Comment by ale5000-git** [comment]
@IzzySoft
See here => https://github.com/deckerst/aves/issues/70#issuecomment-1309203686

**Comment by IzzySoft** [comment]
Yupp. FakeStore v0.1.0 is installed on both devices, so at least in my case that cannot be the reason.

**Comment by ale5000-git** [comment]
It may be a ROM issue, since usually it doesn't work when microG isn't a system app.

To make it working the ROM first need this patch to allow backend outside system: https://github.com/microg/UnifiedNlp/blob/master/patches/android_frameworks_base-N.patch
(the patch is for Nougat but I think it can be adapted also to other versions)

But it isn't enough, it also need this configuration in the framework:
```
    <bool name="config_enableNetworkLocationOverlay" translatable="false">true</bool>

    <bool name="config_enableGeocoderOverlay" translatable="false">true</bool>

    <string-array name="config_locationProviderPackageNames" translatable="false">
        <item>com.google.android.gms</item>
        <item>com.android.location.fused</item>
    </string-array>
```

**Comment by SigmaBonder** [comment]
> I think it can be adapted also to other versions

It's not so easy, as the method changed. But we have patches already available for all the versions of Android above Nougat as well. The author of this issue works on Android 10 (Q), for which the standard signature spoofing patch can be found [here](https://github.com/microg/GmsCore/pull/957/files). When I build an OS with microG, though, I use [CalyxOS's version](https://review.calyxos.org/c/CalyxOS/platform_frameworks_base/+/388) (this one is from Android 11, but it will work on 10, too). It changes things so that only microG is allowed to spoof signature, and only a specific one at that. It also raises the permission level to `signature|privileged`. If working with upstream microG binaries, the permission has to be renamed back to `FAKE_PACKAGE_SIGNATURE`.

I'm working on Android 12, where I didn't enable `config_enableNetworkLocationOverlay` and `config_enableGeocoderOverlay` and it works fine, so I'm not sure it is necessary — but it probably wouldn't hurt. Besides `config_locationProviderPackageNames`, I also add `config_locationExtraPackageNames` with backends that I use, in order to automatically grant them permissions to always use precise location in the background.

**Comment by ale5000-git** [comment]
I was talking about the patch to allow location backends (UnifiedNlp inside microG or UnifiedNlp) outside system partition that isn't the same of the signature spoofing patch.

**Comment by ale5000-git** [comment]
When config_enableNetworkLocationOverlay and/or config_enableGeocoderOverlay are enabled it will pick them from config_locationProviderPackageNames.

Instead if they are disabled it will use config_networkLocationProviderPackageName and config_geocoderProviderPackageName respectively so it does matter.

I'm not sure if config_locationExtraPackageNames is affected though.

**Comment by SigmaBonder** [comment]
Sorry, I must have had a brain fart. The location spoofing works on the author's system, after all.

**Comment by ale5000-git** [comment]
The only thing that I can think is that he may have config_enableGeocoderOverlay disabled.

**Comment by IzzySoft** [comment]
@ale5000-git I've just send those details to the related [ShiftOS forum thread](https://forum.shiftphones.com/threads/anleitung-zur-wirklichen-einfachen-installation-von-shiftos-l-mit-microg-fuer-alltagstaugliches-handy.2270/page-11#post-44483) and pinged their dev to take a look. Will report back when I get a reply (unless amartinez responds here himself).

I know that signature spoofing is included with their ROM (permission was requested, and other backends work fine).

Thanks for all those details! Looks promising we can get that sorted out.

**Comment by amartinz** [comment]
> It may be a ROM issue, since usually it doesn't work when microG isn't a system app.

It was a ROM issue, thanks for all the help and guidance!

We split overlays in G (with GMS) and L (without GMS) variants and the location overlays were only applied to the G variant but not L.

I have applied the following overlays and it works now:
```
    <!-- Enable overlay for all location components. -->
    <bool name="config_enableNetworkLocationOverlay" translatable="false">true</bool>
    <bool name="config_enableFusedLocationOverlay" translatable="false">true</bool>
    <bool name="config_enableGeocoderOverlay" translatable="false">true</bool>
    <bool name="config_enableGeofenceOverlay" translatable="false">true</bool>

    <!-- Sets the package names whose certificates should be used to
         verify location providers are allowed to be loaded. -->
    <string-array name="config_locationProviderPackageNames" translatable="false">
        <item>com.google.android.gms</item>
        <item>com.android.location.fused</item>
        <item>com.qualcomm.location</item>
    </string-array>
```

**Comment by IzzySoft** [comment]
I'll test it soon™ – but the screenshots Alex shared with me look like it's solved. Thanks a lot to you, @amartinz!

**Comment by IzzySoft** [comment]
I hereby solemnly proclaim the fix working for me :partying_face: Thanks to all for your help!

**Comment by ale5000-git** [comment]
Good :)
