### ISSUE TITLE
NominatimNlpBackend  https://f-droid.org/en/packages/org.microg.nlp.backend.nominatim/

### ISSUE THREAD

**Issue by Osmandfan** [microg/NominatimGeocoderBackend#30]
I installed this app from F-droid. Someone gave me an advise to install this to fix a problem with the GPS on my Fairphone 3 with  e/OS.
I was supposed to help getting a better GPS signal but it does not help. How do I uninstall this? I can't find it in the app list.

Thank you very much for your help and time

**Affected app**
Name: [e.g. WhatsApp]
Package id: [e.g. com.whatsapp]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
Android Version: [e.g. 10]
Custom ROM: [e.g. LineageOS 17.1]

**microG**
microG Core version: [e.g. 0.2.13.203915]
microG Self-Check results: [e.g. All ticked]

**Additional context**

**Comment by ale5000-git** [comment]
It is in app list as "Nominatim Geocoder Backend".
If you have adb you can use `adb uninstall org.microg.nlp.backend.nominatim`

**Comment by Osmandfan** [comment]
> 

Thank you very much @ale5000-git  I am sorry can't find it in the app list.  I have it installed on my fairphone with e/os. I installed ADB. Connected phone in PTP mode. Put it in debug mode. But in powershell the adb command is not recognized. I am in the correct folder when giving the command. Is there another way to get rid of this api?

**Comment by JonnyTech** [comment]
For `adb` install Android SDK Platform Tools: https://developer.android.com/studio/releases/platform-tools

**Comment by Osmandfan** [comment]
> For `adb` install Android SDK Platform Tools: https://developer.android.com/studio/releases/platform-tools

Thank you very much @JonnyTech I did install adb. Connected the phone through PTP. But when I run the uninstall command as given by @ale5000-git  
adb uninstall org.microg.nlp.backend.nominatim

This error message is what I get.

![2023-01-26 13_28_13-Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/119345656/214836160-20cc51c4-201f-478a-beb0-b1a8b1633dab.png)

**Comment by JonnyTech** [comment]
As per the message shown on the screen:

`.\adb uninstall org.microg.nlp.backend.nominatim`

Note the `.\` at the start of the line.

**Comment by Osmandfan** [comment]
Sorry overlooked it. Thank you very much.

**Comment by Osmandfan** [comment]
> As per the message shown on the screen:
> 
> `.\adb uninstall org.microg.nlp.backend.nominatim`
> 
> Note the `.\` at the start of the line.

I am one step futher thank you. 
Now it does not recognize Nominatim which is definitely installed on the phone.
The Phone itself gets recognized ones connected. 
![2023-01-26 16_23_25-Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/119345656/214876196-41381f2c-84fc-4458-b1c5-61e23c1a1453.png)

**Comment by ale5000-git** [comment]
It is just saying that it don't see the phone.
adb don't use PTP, you should enable adb in developers options on the phone.
You can disable it again at the end, after running the adb command.

**Comment by Osmandfan** [comment]
> It is just saying that it don't see the phone. adb don't use PTP, you should enable adb in developers options on the phone. You can disable it again at the end, after running the adb command.

Yet one step further. Enabled debug. Allowed acces in conformation dialog.  Tried Kill server command but still this error is showing up.

Haha this seems such a simple command... but sometimes simple thing become complex...

Do you have a new suggestion perhaps? Thank you and have a good weekend!  
![2023-01-27 15_28_04-NominatimNlpBackend https___f-droid org_en_packages_org microg nlp backend nomin](https://user-images.githubusercontent.com/119345656/215111333-4a2e6305-d8fe-4364-9321-662eb04fac8f.png)

**Comment by JonnyTech** [comment]
`.\adb devices`

Your phone should be listed as connected.

`.\adb shell cmd package list packages`

All installed apps will be listed.

`.\adb shell pm uninstall -k --user 0 app-from-list`

Uninstall app from previous list.

`.\adb shell pm uninstall -k --user 0 org.microg.nlp.backend.nominatim`

Make sure `org.microg.nlp.backend.nominatim` was on the list, modify package name if required.

**Comment by Osmandfan** [comment]
> `.\adb devices`
> 
> Your phone should be listed as connected.
> 
> `.\adb shell cmd package list packages`
> 
> All installed apps will be listed.
> 
> `.\adb shell pm uninstall -k --user 0 app-from-list`
> 
> Uninstall app from previous list.
> 
> `.\adb shell pm uninstall -k --user 0 org.microg.nlp.backend.nominatim`
> 
> Make sure `org.microg.nlp.backend.nominatim` was on the list, modify package name if required.

Thank you very much. I will check it right away and let you know asap.


Thank you so much, It finally worked.  Haven't got a clue what I have been doing :-) but it worked out well.

this command was not recognized. `.\adb shell pm uninstall -k --user 0 app-from-list`

But the last command was. Happy camper here.
![2023-01-27 15_57_18-Selecteren Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/119345656/215118689-7d9b9b16-b340-42f7-9622-557b0e07affa.png)
![2023-01-27 16_02_34-Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/119345656/215118695-1966b552-2108-4c2c-adc1-bc6d155565cf.png)

**Comment by JonnyTech** [comment]
> this command was not recognized. .\adb shell pm uninstall -k --user 0 app-from-list

Sorry, I thought it was obvious that `app-from-list` should have been replaced with the app name from the list.

> Happy camper here.

Glad to have helped. Can you please close this issue now?
